import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
	id 'java-library'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.124'
	id 'org.jetbrains.kotlin.jvm' version '2.1.21'
	id "me.shedaniel.unified-publishing" version "0.1.+"
	id 'org.moddedmc.wiki.toolkit' version '0.3.2'
}

def ENV = System.getenv()
def isLocal = !ENV.containsKey("GITHUB_RUN_NUMBER")

def archiveName = "${mod_id.replace("_", "-")}-${minecraft_version}"

version = "${mod_version}-${isLocal ? "local.${Instant.now().epochSecond}" : "build.${ENV.GITHUB_RUN_NUMBER}"}"
group = project.mod_group_id
base.archivesName = archiveName

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
compileKotlin.compilerOptions.jvmTarget = JvmTarget.JVM_21

neoForge {

	enable {
		version = neo_version
		validateAccessTransformers = ENV.CI != "true"
		disableRecompilation = ENV.CI == "true"

		accessTransformers {
			publish(project.file('src/main/resources/META-INF/accesstransformer.cfg'))
		}
	}

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {
		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'

			logLevel = org.slf4j.event.Level.DEBUG
		}

		"Client-One" {
			client()
			ideName = "Client One"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

			if (ENV.MC_CLIENT_ARGS) {
				programArguments.addAll(ENV.MC_CLIENT_ARGS.split(' '))
			}

			gameDirectory = file 'runs/client'
		}

		"Client-Two" {
			client()
			ideName = "Client Two"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

			gameDirectory = file 'runs/client'

			if (ENV.MC_CLIENT_2_ARGS) {
				programArguments.addAll(ENV.MC_CLIENT_2_ARGS.split(' '))
			}
		}

		server {
			server()
			ideName = "Server"
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

			gameDirectory = file 'runs/server'
		}

		gameTestServer {
			type = "gameTestServer"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		data {
			data()

			gameDirectory = file 'runs/client'

			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}

		"Wiki-Export-Client" {
			client()
			gameDirectory = file 'runs/wiki_exporter'
			systemProperty 'item_asset_export.render.namespaces', 'geneticsresequenced'
		}
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

repositories {
	mavenLocal()

	maven {
		name = 'Kotlin for Forge'
		url = 'https://thedarkcolour.github.io/KotlinForForge/'
		content { includeGroup "thedarkcolour" }
	}

	repositories {
		maven {
			name = "Illusive Soulworks maven"
			url = "https://maven.theillusivec4.top/"
		}
	}

	//For REI
	repositories {
		maven { url "https://maven.shedaniel.me" }
	}

	// For Modonomicon
	maven {
		url "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
		content {
			includeGroup "com.klikli_dev"
		}
	}

	//Cursemaven
	exclusiveContent {
		forRepository {
			maven {
				url "https://cursemaven.com"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}

	// For EMI
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}

	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}

	maven {
		url 'https://jitpack.io'
		content {
			includeGroup "com.github.rtyley"
		}
	}

	maven {
		url "https://maven.latvian.dev/releases"
		content {
			includeGroup "dev.aaronhowser.mods"
			includeGroup("dev.latvian.mods")
			includeGroup("dev.latvian.apps")
		}
	}

	maven {
		url "https://maven.sinytra.org"
	}

}

dependencies {
	implementation "thedarkcolour:kotlinforforge-neoforge:${kff_version}"

	compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
	runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"

	implementation("com.klikli_dev:modonomicon-1.21.1-neoforge:${modonomicon_version}") { transitive = false }

	boolean useEmi = true

	compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
	if (useEmi) {
		runtimeOnly "dev.emi:emi-neoforge:${emi_version}"
	}

	compileOnly("mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}")
	if (!useEmi) {
		runtimeOnly("mezz.jei:jei-${mc_version}-neoforge:${jei_version}")
	}

	compileOnly "dev.aaronhowser.mods:patchoulidatagen-${pdg_version}"
	implementation "dev.aaronhowser.mods:aaron-1.21.1:${aaron_lib_version}"

	runtimeOnly "org.sinytra:item-asset-export-neoforge:1.0.2+1.21"

	implementation "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"
	implementation "dev.latvian.mods:rhino:${rhino_version}"
}

tasks.withType(ProcessResources).configureEach {
	var replaceProperties = [
			minecraft_version      : minecraft_version,
			minecraft_version_range: minecraft_version_range,
			neo_version            : neo_version,
			neo_version_range      : neo_version_range,
			loader_version_range   : loader_version_range,
			mod_id                 : mod_id,
			mod_name               : mod_name,
			mod_license            : mod_license,
			mod_version            : mod_version,
			mod_authors            : mod_authors,
			mod_description        : mod_description,
			aaron_lib_version_range: aaron_lib_version_range,
			kff_version_range      : kff_version_range
	]
	inputs.properties replaceProperties

	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties
	}
}

publishing {
	publications {
		mavenNeoForge(MavenPublication) {
			artifactId = archiveName
			from components.java
		}
	}

	repositories {
		if (ENV.MAVEN_URL && ENV.MAVEN_USERNAME && ENV.MAVEN_TOKEN) {
			maven {
				url = ENV.MAVEN_URL
				credentials {
					username = ENV.MAVEN_USERNAME
					password = ENV.MAVEN_TOKEN
				}
			}
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

java {
	withSourcesJar()
	withJavadocJar()
}

unifiedPublishing {
	project {
		displayName = "Genetics: Resequenced ${project.minecraft_version} ${project.version}"
		gameVersions = [project.minecraft_version]
		gameLoaders = ["neoforge"]

		changelog = "https://github.com/Berry-Club/Genetics-Resequenced/blob/master/CHANGELOG.md#" + project.mod_version.toString().replace(".", "")

		mainPublication jar

		relations {
			depends {
				curseforge = modrinth = "kotlin-for-forge"
			}

			depends {
				curseforge = modrinth = "aaron"
			}

			optional {
				curseforge = modrinth = "modonomicon"
			}

			optional {
				curseforge = modrinth = "patchouli"
			}

			optional {
				curseforge = modrinth = "oracle-index"
			}
		}

		if (ENV.CURSEFORGE_KEY) {
			curseforge {
				token = ENV.CURSEFORGE_KEY
				id = project.curseforge_id
			}
		}

		if (ENV.MODRINTH_TOKEN) {
			modrinth {
				token = ENV.MODRINTH_TOKEN
				id = project.modrinth_id
			}
		}

	}
}

wiki {
	wikiAccessToken = ENV.MODDED_MC_WIKI_TOKEN

	docs {
		geneticsresequenced {
			root = file('docs/geneticsresequenced')
		}
	}
}

tasks.named('processResources') {
	from("$rootDir/docs") {
		into "assets/oracle_index/books"
		exclude "assets/items/**"
	}
	doLast {
		println "processResources executed: wiki folder copied into assets/oracle_index"
	}
}