kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.16
forge_version_range=[47.4,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=geneticsresequenced
mod_name=Genetics: Resequenced
mod_license=MIT
mod_version=1.11.4
mc_version=1.21.1
mod_group_id=dev.aaronhowser.mods
mod_authors=aaronhowser1
mod_description=Extract mobs' Genes to gain their powers!

kff_version=4.12.0
kff_version_range=[4.12.0,)

aaron_lib_version_range=[1.7.0,)
aaron_lib_version=1.7.0-build.9

pdg_version=1.21.1:1.0.0-build.10
curios_version=9.5.1+1.21.1
emi_version=1.1.22+1.21.1
jei_version=19.21.2.313
mekanism_version=1.21.1-10.7.7.64
kubejs_version=2101.7.1-build.192
modonomicon_version=1.114.2

curseforge_id=1040563
modrinth_id=56QtOIBy