kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.10-beta
loader_version_range=[6,)

mod_id=geneticsresequenced
mod_name=Genetics: Resequenced
mod_license=MIT
mod_version=1.12.3
mc_version=1.21.1
mod_group_id=dev.aaronhowser.mods
mod_authors=aaronhowser1
mod_description=Extract mobs' Genes to gain their powers!

kff_version=6.2.0
kff_version_range=[6.2.0,)

aaron_lib_version_range=[1.10,)
aaron_lib_version=1.10.0-build.9

#pdg_version=1.21.1:1.0.0-build.10
#curios_version=9.5.1+1.21.1
#emi_version=1.1.22+1.21.1
#jei_version=19.21.2.313
#modonomicon_version=1.114.2

curseforge_id=1040563
modrinth_id=56QtOIBy