modLoader="kotlinforforge"
loaderVersion="[3,)"
license='LGPL'

[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="ExampleMod"
credits="The ExampleMod dev team"
authors="ExampleModAuthor"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
