modLoader="kotlinforforge"
loaderVersion="[3,)"
license='MIT'

[[mods]]
modId="geneticsresequenced"
version="${file.jarVersion}"
displayName="Genetics Resequenced"
#credits="The ExampleMod dev team"
authors="aaronhowser1"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.geneticsresequenced]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geneticsresequenced]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
