package dev.aaronhowser.mods.geneticsresequenced

import dev.aaronhowser.mods.geneticsresequenced.api.capability.genes.Gene
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.effect.MobEffects

@Suppress("unused", "MemberVisibilityCanBePrivate")
object DefaultGenes {

    fun registerGenes() {
        // Doesn't do anything, but it loads the object which initializes the genes
    }

    private fun registerGene(geneId: String): Gene = Gene(ResourceLocation(GeneticsResequenced.ID, geneId))

    val HASTE_2 = registerGene("haste_2")
        .setTranslationKey("gene.geneticsresequenced.haste_2")
        .setAmountNeeded(50)
        .setPotion(MobEffects.DIG_SPEED, 2)
        .build()
    val EFFICIENCY_4 = registerGene("efficiency_4")
        .setTranslationKey("gene.geneticsresequenced.efficiency_4")
        .setAmountNeeded(50)
        .build()
    val REGENERATION_4 = registerGene("regeneration_4")
        .setTranslationKey("gene.geneticsresequenced.regeneration_4")
        .setAmountNeeded(50)
        .setPotion(MobEffects.REGENERATION, 4)
        .build()
    val SPEED_4 = registerGene("speed_4")
        .setTranslationKey("gene.geneticsresequenced.speed_4")
        .setAmountNeeded(50)
        .setPotion(MobEffects.MOVEMENT_SPEED, 4)
        .build()
    val SPEED_2 = registerGene("speed_2")
        .setTranslationKey("gene.geneticsresequenced.speed_2")
        .setAmountNeeded(50)
        .setPotion(MobEffects.MOVEMENT_SPEED, 2)
        .setMutatesInto(SPEED_4)
        .build()
    val RESISTANCE_2 = registerGene("resistance_2")
        .setTranslationKey("gene.geneticsresequenced.resistance_2")
        .setAmountNeeded(50)
        .setPotion(MobEffects.DAMAGE_RESISTANCE, 2)
        .build()
    val STRENGTH_2 = registerGene("strength_2")
        .setTranslationKey("gene.geneticsresequenced.strength_2")
        .setAmountNeeded(50)
        .setPotion(MobEffects.DAMAGE_BOOST, 2)
        .build()
    val MEATY_2 = registerGene("meaty_2")
        .setTranslationKey("gene.geneticsresequenced.meaty_2")
        .setAmountNeeded(50)
        .build()
    val MORE_HEARTS_2 = registerGene("more_hearts_2")
        .setTranslationKey("gene.geneticsresequenced.more_hearts_2")
        .setAmountNeeded(50)
        .build()
    val INVISIBLE = registerGene("invisible")
        .setTranslationKey("gene.geneticsresequenced.invisibility")
        .setAmountNeeded(50)
        .setPotion(MobEffects.INVISIBILITY, 1)
        .build()
    val FLIGHT = registerGene("flight")
        .setTranslationKey("gene.geneticsresequenced.flight")
        .setAmountNeeded(50)
        .build()
    val LUCK = registerGene("luck")
        .setTranslationKey("gene.geneticsresequenced.luck")
        .setAmountNeeded(50)
        .setPotion(MobEffects.LUCK, 1)
        .build()
    val SCARE_ZOMBIES = registerGene("scare_zombies")
        .setTranslationKey("gene.geneticsresequenced.scare_zombies")
        .setAmountNeeded(50)
        .build()
    val SCARE_SPIDERS = registerGene("scare_spiders")
        .setTranslationKey("gene.geneticsresequenced.scare_spiders")
        .setAmountNeeded(50)
        .build()
    val THORNS = registerGene("thorns")
        .setTranslationKey("gene.geneticsresequenced.thorns")
        .setAmountNeeded(12)
        .build()
    val CLAWS_2 = registerGene("claws_2")
        .setTranslationKey("gene.geneticsresequenced.claws_2")
        .setAmountNeeded(50)
        .build()

    //Standard list
    val DRAGONS_BREATH = registerGene("dragons_breath")
        .setTranslationKey("gene.geneticsresequenced.dragons_breath")
        .setAmountNeeded(20)
        .build()
    val EAT_GRASS = registerGene("eat_grass")
        .setTranslationKey("gene.geneticsresequenced.eat_grass")
        .setAmountNeeded(16)
        .build()
    val EMERALD_HEART = registerGene("emerald_heart")
        .setTranslationKey("gene.geneticsresequenced.emerald_heart")
        .setAmountNeeded(30)
        .build()
    val ENDER_DRAGON_HEALTH = registerGene("ender_dragon_health")
        .setTranslationKey("gene.geneticsresequenced.ender_dragon_health")
        .setAmountNeeded(60)
        .build()
    val EXPLOSIVE_EXIT = registerGene("explosive_exit")
        .setTranslationKey("gene.geneticsresequenced.explosive_exit")
        .setAmountNeeded(20)
        .build()
    val FIRE_PROOF = registerGene("fire_proof")
        .setTranslationKey("gene.geneticsresequenced.fire_proof")
        .setAmountNeeded(24)
        .build()
    val ITEM_MAGNET = registerGene("item_magnet")
        .setTranslationKey("gene.geneticsresequenced.item_magnet")
        .setAmountNeeded(30)
        .build()
    val JUMP_BOOST = registerGene("jump_boost")
        .setTranslationKey("gene.geneticsresequenced.jump_boost")
        .setMutatesInto(FLIGHT)
        .setAmountNeeded(10)
        .setPotion(MobEffects.JUMP, 1)
        .build()
    val MILKY = registerGene("milky")
        .setTranslationKey("gene.geneticsresequenced.milky")
        .setAmountNeeded(12)
        .build()
    val MORE_HEARTS = registerGene("more_hearts")
        .setTranslationKey("gene.geneticsresequenced.more_hearts")
        .setAmountNeeded(40)
        .setMutatesInto(MORE_HEARTS_2)
        .build()
    val NIGHT_VISION = registerGene("night_vision")
        .setTranslationKey("gene.geneticsresequenced.night_vision")
        .setAmountNeeded(16)
        .setPotion(MobEffects.NIGHT_VISION, 1)
        .build()
    val NO_FALL_DAMAGE = registerGene("no_fall_damage")
        .setTranslationKey("gene.geneticsresequenced.no_fall_damage")
        .setAmountNeeded(30)
        .build()
    val PHOTOSYNTHESIS = registerGene("photosynthesis")
        .setTranslationKey("gene.geneticsresequenced.photosynthesis")
        .setAmountNeeded(40)
        .setMutatesInto(THORNS)
        .build()
    val POISON_IMMUNITY = registerGene("poison_immunity")
        .setTranslationKey("gene.geneticsresequenced.poison_immunity")
        .setAmountNeeded(24)
        .build()
    val RESISTANCE = registerGene("resistance")
        .setTranslationKey("gene.geneticsresequenced.resistance")
        .setAmountNeeded(30)
        .setPotion(MobEffects.DAMAGE_RESISTANCE, 1)
        .setMutatesInto(RESISTANCE_2)
        .build()
    val KEEP_INVENTORY = registerGene("keep_inventory")
        .setTranslationKey("gene.geneticsresequenced.keep_inventory")
        .setAmountNeeded(40)
        .build()
    val SCARE_CREEPERS = registerGene("scare_creepers")
        .setTranslationKey("gene.geneticsresequenced.scare_creepers")
        .setAmountNeeded(20)
        .setMutatesInto(SCARE_ZOMBIES)
        .build()
    val SCARE_SKELETONS = registerGene("scare_skeletons")
        .setTranslationKey("gene.geneticsresequenced.scare_skeletons")
        .setAmountNeeded(20)
        .setMutatesInto(SCARE_SPIDERS)
        .build()
    val SHOOT_FIREBALLS = registerGene("shoot_fireballs")
        .setTranslationKey("gene.geneticsresequenced.shoot_fireballs")
        .setAmountNeeded(24)
        .build()
    val SLIMY_DEATH = registerGene("slimy_death")
        .setTranslationKey("gene.geneticsresequenced.slimy_death")
        .setAmountNeeded(60)
        .build()
    val SPEED = registerGene("speed")
        .setTranslationKey("gene.geneticsresequenced.speed")
        .setAmountNeeded(20)
        .setPotion(MobEffects.MOVEMENT_SPEED, 1)
        .setMutatesInto(SPEED_2)
        .build()
    val STRENGTH = registerGene("strength")
        .setTranslationKey("gene.geneticsresequenced.strength")
        .setAmountNeeded(20)
        .setPotion(MobEffects.DAMAGE_BOOST, 1)
        .setMutatesInto(STRENGTH_2)
        .build()
    val TELEPORT = registerGene("teleport")
        .setTranslationKey("gene.geneticsresequenced.teleport")
        .setAmountNeeded(24)
        .setMutatesInto(FLIGHT)
        .build()
    val WATER_BREATHING = registerGene("water_breathing")
        .setTranslationKey("gene.geneticsresequenced.water_breathing")
        .setAmountNeeded(16)
        .build()
    val WOOLY = registerGene("wooly")
        .setTranslationKey("gene.geneticsresequenced.wooly")
        .setAmountNeeded(12)
        .build()
    val WITHER_HIT = registerGene("wither_hit")
        .setTranslationKey("gene.geneticsresequenced.wither_hit")
        .setAmountNeeded(20)
        .build()
    val WITHER_PROOF = registerGene("wither_proof")
        .setTranslationKey("gene.geneticsresequenced.wither_proof")
        .setAmountNeeded(40)
        .build()
    val XP_MAGNET = registerGene("xp_magnet")
        .setTranslationKey("gene.geneticsresequenced.xp_magnet")
        .setAmountNeeded(30)
        .build()
    val STEP_ASSIST = registerGene("step_assist")
        .setTranslationKey("gene.geneticsresequenced.step_assist")
        .setAmountNeeded(10)
        .build()
    val INFINITY = registerGene("infinity")
        .setTranslationKey("gene.geneticsresequenced.infinity")
        .setAmountNeeded(30)
        .build()
    val BIOLUMINESCENCE = registerGene("bioluminescence")
        .setTranslationKey("gene.geneticsresequenced.bioluminescence")
        .setAmountNeeded(16)
        .build()
    val CYBERNETIC = registerGene("cybernetic")
        .setTranslationKey("gene.geneticsresequenced.cybernetics")
        .setAmountNeeded(30)
        .build()
    val LAY_EGG = registerGene("lay_egg")
        .setTranslationKey("gene.geneticsresequenced.lay_eggs")
        .setAmountNeeded(12)
        .build()
    val MEATY = registerGene("meaty")
        .setTranslationKey("gene.geneticsresequenced.meaty")
        .setAmountNeeded(12)
        .setMutatesInto(MEATY_2)
        .build()
    val NO_HUNGER = registerGene("no_hunger")
        .setTranslationKey("gene.geneticsresequenced.no_hunger")
        .setAmountNeeded(30)
        .build()
    val CLAWS = registerGene("claws")
        .setTranslationKey("gene.geneticsresequenced.claws")
        .setAmountNeeded(20)
        .setMutatesInto(CLAWS_2)
        .build()
    val HASTE = registerGene("haste")
        .setTranslationKey("gene.geneticsresequenced.haste")
        .setAmountNeeded(30)
        .setPotion(MobEffects.DIG_SPEED, 1)
        .setMutatesInto(HASTE_2)
        .build()
    val EFFICIENCY = registerGene("efficiency")
        .setTranslationKey("gene.geneticsresequenced.efficiency")
        .setAmountNeeded(30)
        .setMutatesInto(EFFICIENCY_4)
        .build()
    val WALL_CLIMBING = registerGene("wall_climbing")
        .setTranslationKey("gene.geneticsresequenced.climb_walls")
        .setAmountNeeded(40)
        .build()
    val MOB_SIGHT = registerGene("mob_sight")
        .setTranslationKey("gene.geneticsresequenced.mob_sight")
        .setAmountNeeded(16)
        .build()
    val REGENERATION = registerGene("regeneration")
        .setTranslationKey("gene.geneticsresequenced.regeneration")
        .setAmountNeeded(60)
        .setPotion(MobEffects.REGENERATION, 1)
        .setMutatesInto(REGENERATION_4)
        .build()

    //Negative effects
    val POISON = registerGene("poison")
        .setTranslationKey("gene.geneticsresequenced.poison_2")
        .setAmountNeeded(1)
        .setPotion(MobEffects.POISON, 1)
        .setNegative()
        .build()
    val POISON_4 = registerGene("poison_4")
        .setTranslationKey("gene.geneticsresequenced.poison_4")
        .setAmountNeeded(1)
        .setPotion(MobEffects.POISON, 4)
        .setNegative()
        .build()
    val WITHER = registerGene("wither")
        .setTranslationKey("gene.geneticsresequenced.wither_2")
        .setAmountNeeded(1)
        .setPotion(MobEffects.WITHER, 1)
        .setNegative()
        .build()
    val WEAKNESS = registerGene("weakness")
        .setTranslationKey("gene.geneticsresequenced.weakness")
        .setAmountNeeded(1)
        .setPotion(MobEffects.WEAKNESS, 1)
        .setNegative()
        .build()
    val BLINDNESS = registerGene("blindness")
        .setTranslationKey("gene.geneticsresequenced.blindness")
        .setAmountNeeded(1)
        .setPotion(MobEffects.BLINDNESS, 1)
        .setNegative()
        .build()
    val SLOWNESS = registerGene("slowness")
        .setTranslationKey("gene.geneticsresequenced.slowness")
        .setAmountNeeded(1)
        .setPotion(MobEffects.MOVEMENT_SLOWDOWN, 1)
        .setNegative()
        .build()
    val SLOWNESS_4 = registerGene("slowness_4")
        .setTranslationKey("gene.geneticsresequenced.slowness_4")
        .setAmountNeeded(1)
        .setPotion(MobEffects.MOVEMENT_SLOWDOWN, 4)
        .setNegative()
        .build()
    val SLOWNESS_6 = registerGene("slowness_6")
        .setTranslationKey("gene.geneticsresequenced.slowness_6")
        .setAmountNeeded(1)
        .setPotion(MobEffects.MOVEMENT_SLOWDOWN, 6)
        .setNegative()
        .build()
    val NAUSEA = registerGene("nausea")
        .setTranslationKey("gene.geneticsresequenced.nausea")
        .setAmountNeeded(1)
        .setPotion(MobEffects.CONFUSION, 1)
        .setNegative()
        .build()
    val HUNGER = registerGene("hunger")
        .setTranslationKey("gene.geneticsresequenced.hunger")
        .setAmountNeeded(1)
        .setPotion(MobEffects.HUNGER, 1)
        .setNegative()
        .build()
    val FLAME = registerGene("flame")
        .setTranslationKey("gene.geneticsresequenced.flambe")
        .setAmountNeeded(1)
        .setNegative()
        .build()
    val CURSED = registerGene("cursed")
        .setTranslationKey("gene.geneticsresequenced.cursed")
        .setAmountNeeded(1)
        .setPotion(MobEffects.UNLUCK, 1)
        .setNegative()
        .build()
    val LEVITATION = registerGene("levitation")
        .setTranslationKey("gene.geneticsresequenced.levitation")
        .setAmountNeeded(1)
        .setPotion(MobEffects.LEVITATION, 1)
        .setNegative()
        .build()
    val MINING_WEAKNESS = registerGene("mining_weakness")
        .setTranslationKey("gene.geneticsresequenced.mining_weakness")
        .setAmountNeeded(1)
        .setPotion(MobEffects.DIG_SLOWDOWN, 1)
        .setNegative()
        .build()
    val DEAD_CREEPERS = registerGene("dead_creepers")
        .setTranslationKey("gene.geneticsresequenced.green_death")
        .setAmountNeeded(1)
        .setNegative()
        .build()
    val DEAD_UNDEAD = registerGene("dead_undead")
        .setTranslationKey("gene.geneticsresequenced.undeath")
        .setAmountNeeded(1)
        .setNegative()
        .build()
    val DEAD_OLD_AGE = registerGene("dead_old_age")
        .setTranslationKey("gene.geneticsresequenced.gray_death")
        .setAmountNeeded(1)
        .setNegative()
        .build()
    val DEAD_HOSTILE = registerGene("dead_hostile")
        .setTranslationKey("gene.geneticsresequenced.white_death")
        .setAmountNeeded(1)
        .setNegative()
        .build()
    val DEAD_ALL = registerGene("dead_all")
        .setTranslationKey("gene.geneticsresequenced.black_death")
        .setAmountNeeded(1)
        .setNegative()
        .build()
    val REALLY_DEAD_ALL = registerGene("really_dead_all")
        .setTranslationKey("gene.geneticsresequenced.void_death")
        .setAmountNeeded(1)
        .setNegative()
        .build()
}